language: node_js
node_js:
  - 10
script:
  - cd web
  - yarn
  - yarn lint
  - yarn build
  - cd build 
  - mkdir admin
  - cd ../../
  - cd functions
  - yarn
  - yarn test
  - cd ../
  - cd admin-web
  - yarn
  - yarn build
  - cp -a ./build/static/. ../web/build/static
  - cp ./build/index.html ../web/build/admin 
  - cd ../
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: OHOwnipwZBB/vXTMk7RbPM4ylO3VvoACX0Uao/FNx4/JM7gAOtCXCJeZv/CdC4KGhy1YhSStMFU6F0G1aFkZ2zPD6QigF9I2YLl7JTkGq/9gdow2fAgTjIuM5HPcvMMOo6VGvrMKpc1g67dQewuNzx3XJtY65ZG+9jWQtPdd1U0IsRtLr+mw4gYKvBI6W6leToOCpzJbUKIEMKpAkvOoZHBhlfPjXCZCsR1kzpx0tVwKXz5+JGRS76Zyi03h5RLlwzkOPzRjyIDqLILvJaHNYpjkGE6T1akO+fUk5ZITwq228Yt/JExnKFwS7qyl6l9kKPrPRn1qMrOaSVa7cLADaXJfuuYtEUFknWUZFoYBZGFj5fMR7CTkq8ez0xFoH0xWJGLcEePv0lSQLKgiSKVRZeE/Ml5hySwJiEZaFOUevkijM9wcGk/SrbjepqPpTZMicX2S8pDKWsTY5fnLYgOT6hULIR6ufhwx5U4L3Fhzoqo4be8BkHD6iZvS/3NFIso7LlFBrNHopf+OL3crEUY5K75DqLTKxRl1YoIybomeF2tfuC/0OipephNT7sIwpwzioNeKVaH98nHNWywELVv8MjogLOpX4D75QdNT83mpgLSOSWHbUFyaPEaLako/VzSUg5E+27UU9NRMO3x1oSszEtPtrzq7X+S40ENQsp+9j/k=
